### ISSUE TITLE
Error on import: JavascriptError: TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by gamelandianna** [fenglisch/bgg-bulk-upload#3]
I tried using the bulk importer and it's throwing this error:

```
JavascriptError: TypeError: document.querySelector(...) is null
    at Object.throwDecodedError
```
Here's the full stack trace with debugging on:

```
[Success] Access to your existing BGG collection was successful. Found 0 items.
 [Debugging mode] ID's from your FILE:
 15987;330833;231824;252556;47;178900;220775;224037;158899;217321;153318;221194;246701;134342;110327;138161;136063;174430;277400;11170;699;127398;621;50;312484;235507;408420;624;254386;333668;346703;330747;329845;123260;167791;299255;199329;48726;342274;252999;232974;1260;280748;12942;371535;410201
 [Status update] Logging in.
 JavascriptError: TypeError: document.querySelector(...) is null
    at Object.throwDecodedError (/Users/mary/src/bgg-bulk-upload/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/Users/mary/src/bgg-bulk-upload/node_modules/selenium-webdriver/lib/http.js:587:13)
    at Executor.execute (/Users/mary/src/bgg-bulk-upload/node_modules/selenium-webdriver/lib/http.js:515:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (/Users/mary/src/bgg-bulk-upload/node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async addGamesToCollection (/Users/mary/src/bgg-bulk-upload/bgg-bulk-upload.js:198:5) {
  remoteStacktrace: '@https://boardgamegeek.com/login:2:16\n' +
    '@https://boardgamegeek.com/login:3:8\n'
}
```

When the new window opens, it seems like the login isn't going through.

**Comment by PetitMalin** [comment]
Hi same issue for me. 
You have to change and add some code in the bgg-bulk-upload.js file

Change 
`await driver.executeScript(
      `document.querySelector("button[class~='fc-cta-consent']").click();`
    );`

by

`await driver.executeScript(
      `document.querySelector("button[id='c-p-bn']").click();`
    );`

And add right after
 
`await driver.sleep(3000);`

Before 

    `await driver.findElement(By.id("inputUsername")).sendKeys(userName);`

Tested and added 887 games ;) 

Best regards

**Comment by EngineeringMoonBear** [comment]
`    await driver.executeScript(
      `document.querySelector("button[id='c-p-bn']").click();`
    );
    await driver.sleep(3000);`

line 198 needs to be adjusted to this just to clarify the guy above me comment seems the button id in chrome changed, one of the limitations of using frontend to do all these actions haha

**Comment by fenglisch** [comment]
Hey there, I am really sorry for ignoring you so long (I didn't have my Github notifications turned on, but I changed that now).

This issue seems to be solved by the commit  https://github.com/fenglisch/bulk-upload-board-games-into-bgg-collection/pull/2/commits/f0a68910501b1739b8c20572f3aa1c2daa65acef from jsoulet. I'll therefore close the issue for now.

> one of the limitations of using frontend to do all these actions haha

Yeah it's a huge pain in the ass 🙈

**Comment by EngineeringMoonBear** [comment]
My job is selenium frontend testing and google webdriver/lighthouse API :p used to it
