### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by MadWelshWizard** [fenglisch/bgg-bulk-upload#4]
Hi,

I'm getting the following error when I try and run the thing. Firstly I think it's not seeing anything in my CSV file but also it's having an issue with the Chrome Driver/selenium-webdriver. I have run the install thing before and the directory is there. Can you help? Thx

C:\bulk>node bgg-bulk-upload.js collection2.csv -u NSG_Test_Account_001 -p PASSWORD
 [Success] Access to your existing BGG collection was successful. Found 0 items.
 The ChromeDriver could not be found on the current PATH, trying Selenium Manager
Unable to obtain driver using Selenium Manager: Error: Error executing command with C:\bulk\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe,--browser,chrome
WARN    Error getting version of chromedriver 131. Retrying with chromedriver 130 (attempt 1/5)
WARN    Error getting version of chromedriver 130. Retrying with chromedriver 129 (attempt 2/5)
WARN    Error getting version of chromedriver 129. Retrying with chromedriver 128 (attempt 3/5)
WARN    Error getting version of chromedriver 128. Retrying with chromedriver 127 (attempt 4/5)
WARN    Error getting version of chromedriver 127. Retrying with chromedriver 126 (attempt 5/5)
ERROR   The chromedriver version cannot be discovered

C:\bulk\node_modules\selenium-webdriver\chrome.js:175
      throw Error(
            ^

Error: The ChromeDriver could not be found on the current PATH.
      Please download the latest version of the ChromeDriver
      from http://chromedriver.storage.googleapis.com/index.html
      and ensure it can be found on your PATH.
    at new ServiceBuilder (C:\bulk\node_modules\selenium-webdriver\chrome.js:175:13)
    at thenableWebDriverProxy.getDefaultService (C:\bulk\node_modules\selenium-webdriver\chrome.js:264:12)
    at thenableWebDriverProxy.createSession (C:\bulk\node_modules\selenium-webdriver\chromium.js:686:49)
    at thenableWebDriverProxy.createSession (C:\bulk\node_modules\selenium-webdriver\chrome.js:255:13)
    at createDriver (C:\bulk\node_modules\selenium-webdriver\index.js:149:33)
    at Builder.build (C:\bulk\node_modules\selenium-webdriver\index.js:677:16)
    at addGamesToCollection (C:\bulk\bgg-bulk-upload.js:192:6)
    at start (C:\bulk\bgg-bulk-upload.js:344:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.12.0

**Comment by fenglisch** [comment]
Hey @MadWelshWizard , I am really sorry for replying so late. I didn't have my notifications turned on, but I changed that now.

> Firstly I think it's not seeing anything in my CSV file

I don't see an indication for that in your logs. The line " [Success] Access to your existing BGG collection was successful. Found 0 items." is referring to your collection on BGG, not to your file. So if your collection has already games in it, then there is an error. Otherwise the program might have read your collection and the CSV file just fine. You can enable debugging-mode to get more logs (just add `debugging-mode` to your command)

 > but also it's having an issue with the Chrome Driver/selenium-webdriver. I have run the install thing before and the directory is there. 

Yeah that's what it looks like. 

First: Can you try it with Firefox?

Otherwise: If you are on Ubuntu/Debian (Linux) you can try:

```
sudo apt update
sudo apt install chromium-chromedriver
```

Check where ChromeDriver is installed:

`which chromedriver`

If it's missing from PATH, add it:

`export PATH=$PATH:/path/to/chromedriver`

If this does not help or if you are not on Ubuntu/Debian, I can only recommend to seek help from ChatGPT (or DeepSeek or any other AI). This issue seems to be purely related to Selenium, which I am not really experienced in. I am just using it as a tool.
